apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  #annotations:
    #這是你的防禦核心：開啟限流 (Rate Limiting)
    #nginx.ingress.kubernetes.io/limit-rps: "5"
    #允許小幅度的突發流量，增加彈性
    #nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service # 必須對應你 k8s-demo.yaml 裡的 service name
            port:
              number: 80